
DROP TABLE IF EXISTS value_attribute_employee CASCADE;
DROP TABLE IF EXISTS attribute_employee CASCADE;
DROP TABLE IF EXISTS permiso CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS rol CASCADE;

CREATE TABLE rol (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE permiso (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rol_id INT NOT NULL,
	permiso VARCHAR(200) NOT NULL,
	CONSTRAINT fk_permiso_rol FOREIGN KEY (rol_id) REFERENCES rol(id),
	CONSTRAINT uq_permiso UNIQUE (rol_id, permiso)
);

CREATE TABLE employees (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	names VARCHAR(100) NOT NULL,
	lastnames VARCHAR(100) NOT NULL,
	identification_type VARCHAR(2) NOT NULL,
	identification_number VARCHAR(15) NOT NULL,
	password VARCHAR(255),
	rol_id INT,
	CONSTRAINT uq_employees_identification UNIQUE (identification_type, identification_number),
	CONSTRAINT fk_employees_rol FOREIGN KEY (rol_id) REFERENCES rol(id)
);

CREATE TABLE attribute_employee (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id integer,
	name_attribute VARCHAR(100) NOT NULL,
	multiple BOOLEAN DEFAULT FALSE,
	CONSTRAINT uq_employee_attribute UNIQUE (employee_id, name_attribute)
);

CREATE TABLE value_attribute_employee (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	attribute_id integer,
	value_attribute VARCHAR(100) NOT NULL
);