
DROP TABLE IF EXISTS value_attribute_employee CASCADE;
DROP TABLE IF EXISTS attribute_employee CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS rol CASCADE;

CREATE TABLE rol (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT uq_rol_name UNIQUE (name)
);

CREATE TABLE permission (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rol_id INT NOT NULL,
	method VARCHAR(6) NOT NULL,
	endpoint VARCHAR(50) NOT NULL,
	CONSTRAINT fk_permission_rol FOREIGN KEY (rol_id) REFERENCES rol(id),
	CONSTRAINT uq_permission UNIQUE (rol_id, method, endpoint)
);

CREATE TABLE employees (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	names VARCHAR(100) NOT NULL,
	lastnames VARCHAR(100) NOT NULL,
	identification_type VARCHAR(2) NOT NULL,
	identification_number VARCHAR(15) NOT NULL,
	password VARCHAR(255),
	rol_id INT,
	secret VARCHAR(255),
	CONSTRAINT uq_employees_identification UNIQUE (identification_type, identification_number),
	CONSTRAINT fk_employees_rol FOREIGN KEY (rol_id) REFERENCES rol(id)
);

CREATE TABLE attribute_employee (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id integer,
	name_attribute VARCHAR(100) NOT NULL,
	multiple BOOLEAN DEFAULT FALSE,
	CONSTRAINT uq_employee_attribute UNIQUE (employee_id, name_attribute)
);

CREATE TABLE value_attribute_employee (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	attribute_id integer,
	value_attribute VARCHAR(100) NOT NULL
);
