CREATE TABLE IF NOT EXISTS rol (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        asistencial BOOLEAN DEFAULT TRUE,
        CONSTRAINT uq_rol_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS permission (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        rol_id INT NOT NULL,
        method VARCHAR(6) NOT NULL,
        endpoint VARCHAR(50) NOT NULL,
        CONSTRAINT fk_permission_rol FOREIGN KEY (rol_id) REFERENCES rol(id),
        CONSTRAINT uq_permission UNIQUE (rol_id, method, endpoint)
);

CREATE TABLE IF NOT EXISTS employees (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        names VARCHAR(100) NOT NULL,
        lastnames VARCHAR(100) NOT NULL,
        identification_type VARCHAR(2) NOT NULL,
        identification_number VARCHAR(15) NOT NULL,
        password VARCHAR(255),
        rol_id INT,
        secret VARCHAR(255),
        CONSTRAINT uq_employees_identification UNIQUE (identification_type, identification_number),
        CONSTRAINT fk_employees_rol FOREIGN KEY (rol_id) REFERENCES rol(id)
);

CREATE TABLE IF NOT EXISTS attribute_employee (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id integer,
        name_attribute VARCHAR(100) NOT NULL,
        multiple BOOLEAN DEFAULT FALSE,
        CONSTRAINT uq_employee_attribute UNIQUE (employee_id, name_attribute)
);

CREATE TABLE IF NOT EXISTS value_attribute_employee (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        attribute_id integer,
        value_attribute VARCHAR(100) NOT NULL
);
