
DROP TABLE IF EXISTS employees ;
CREATE TABLE employees (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	names VARCHAR(100) NOT NULL,
	lastnames VARCHAR(100) NOT NULL,
	identification_type VARCHAR(2) NOT NULL,
	identification_number VARCHAR(15) NOT NULL,
	password VARCHAR(255),
	rol_id INT,
	secret VARCHAR(255),
	CONSTRAINT uq_employees_identification UNIQUE (identification_type, identification_number)
);
DROP TABLE IF EXISTS attribute_employee ;
CREATE TABLE attribute_employee ( 
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id integer,
	name_attribute VARCHAR(100) NOT NULL,
	multiple BOOLEAN DEFAULT FALSE,
	CONSTRAINT uq_employees_attribute UNIQUE (employee_id, name_attribute)
);
DROP TABLE IF EXISTS value_attribute_employee ;
CREATE TABLE value_attribute_employee ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,attribute_id integer, value_attribute VARCHAR(100) NOT NULL);